name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

    - name: Pull the Cache image
      run: docker pull ghcr.io/betats/vpnsocks:latest

    - name: Build the Docker image
      run: docker build . --tag ghcr.io/betats/vpnsocks:$GITHUB_SHA --cache-from ghcr.io/betats/vpnsocks:latest

    - name: Push the Docker image
      run: docker push ghcr.io/betats/vpnsocks:$GITHUB_SHA
