name: Docker Image CI

on:
  push:
    tags:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        # new login with new container registry url and PAT
        echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
        # # new container registry urls added
        docker pull ghcr.io/betats/vpnsocks:latest
        docker build . --tag ghcr.io/betats/vpnsocks:latest --cache-from ghcr.io/betats/vpnsocks:latest
        docker push ghcr.io/betats/vpnsocks:latest
