name: Release

on:
  push:
    tags:
  schedule:
    - cron: 0 4 * * *

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Build the Docker image
      run: |
        echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
        docker build . --tag ghcr.io/betats/vpnsocks:latest --cache-from ghcr.io/betats/vpnsocks:latest
        docker push ghcr.io/betats/vpnsocks:latest
